sudo: false
cache: pip

language: python

python:
    - "3.6"

install:
    - pip install nose
    - pip install nbconvert
    - pip install nbformat
    - pip install jupyter

script:
    - python -m nose
